version: "3.8"

services:
  mariadb:
    image: mariadb:10.11
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 000000
      MYSQL_DATABASE: findahelper
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build: ./api
    container_name: api
    ports:
      - "8080:8080"
    environment:
      - KTOR_ENV=prod
    depends_on:
      - mariadb

  client:
    build: ./client
    container_name: client
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
    command: npm run dev

volumes:
  db_data:
